<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-FET714UI" ignored="0" name="withdrawal" tests="1" failures="1" timestamp="2021-04-22T17:58:40 IST" time="21.797" errors="0">
  <testcase name="Withdrawal" time="3.715" classname="com.testCases.withdrawal_TestCases">
    <failure type="java.lang.AssertionError" message="expected [Enter the Amount less than 30000] but found [You do not have sufficient Withdrawable balance.]">
      <![CDATA[java.lang.AssertionError: expected [Enter the Amount less than 30000] but found [You do not have sufficient Withdrawable balance.]
at com.pageFactory.withdrawal_POF.maxAmountValidation(withdrawal_POF.java:38)
at com.testCases.withdrawal_TestCases.Withdrawal(withdrawal_TestCases.java:43)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- Withdrawal -->
</testsuite> <!-- withdrawal -->
